FlutterKaigi/confwebsite2021

lib/pages/index.dart, lib/widgets/footer.dart
- Footer
- Code of Conduct
- Privacy Policy
- Contact (Google Form)
=> feat: footer layout

lib/main.dart, lib/router/simple_route.dart, lib/utils/responsive_layout.dart, lib/widgets/footer.dart, lib/widgets/navbar.dart, lib/widgets/social.dart, pubspec.yaml
I think it's better to make this repository modern because it's the website of FlutterKaigi!
=> Apply null safety

l10n.yaml, lib/l10n/app_en.arb, lib/l10n/app_ja.arb, lib/main.dart, lib/widgets/footer.dart, pubspec.lock, pubspec.yaml
fix #13 
日本語と英語のarbファイルを作成し、デフォルトのサポート言語を日本語にしました。
一応、フッターのボタン文字列のみ置き換えてあります。
他にも置き換えたい文字列があれば教えて下さい！
c.f. https://flutter.dev/docs/development/accessibility-and-localization/internationalization
=> l10n support + Japanese and English support

lib/l10n/app_en.arb, lib/l10n/app_ja.arb, lib/widgets/navbar.dart
=> fix: l10n support for navBar

web/index.html
summary or summary_large_image
=> summary_large_image test

lib/widgets/footer.dart, lib/widgets/navbar.dart, lib/widgets/social.dart
#22 
カーソルがアイコンやボタンに合わせた時にラベルにURLを表示するようにした
音声に関しては何もしてません
- ホームボタン以外のボタン・アイコンにカーソルを合わせるとラベルにURLが表示された
- ホームはリンクが "/" だったため、あえて表示していない
=> show labels when cursor hover

lib/widgets/footer.dart, lib/widgets/navbar.dart, lib/widgets/social.dart
Enables mouse operation (`Tab` / `Shift` operation) in a Web browser
=> [A11Y] add mouseCursor

lib/data/staff.dart
- fix staff's twitter link
- change my display name
=> fix staff's twitter link

lib/widgets/cfs_button.dart
=> fix: buttonColor on hovered

lib/l10n/app_en.arb, lib/pages/staff.dart
=> minor wording changes

lib/data/staff.dart
- Change shikanai's name and photo
=> Change Staff Info

lib/pages/index.dart
implement background animation
resolves #5
=> Add background animation

lib/l10n/app_en.arb, lib/l10n/app_ja.arb, lib/widgets/footer.dart, lib/widgets/license_button.dart
=> feat: license button

lib/pages/staff.dart
=> Center staff item content + wrap staff name w/ FittedBox

web/manifest.json
https://flutter-jp.slack.com/archives/C02766DD1DG/p1632212797124900?thread_ts=1632212757.124600&cid=C02766DD1DG
=> Modify App Name

lib/router/simple_route.dart
=> disable maintainState

.github/workflows/firebase-hosting-preview.yml, .github/workflows/firebase-hosting-production.yml, .github/workflows/gh-pages.yml
デスクトップ( `mac` `chrome/safari` )で表示した際、下記現象に対応したPRです 🙏  
(issueなしのPRになります。既に議論済み等の現象であればcloseします )
- 画面の読み込み完了まで、日本語フォントが文字化けする(デスクトップの場合 `canvaskit` がデフォルトで採用される為ですが、少し下に添付した動画のように環境によっては目立つのでPR作成しました 👀  )
- 読み込み完了後も漢字が中華フォントになっている (現状目立つのは `覧` くらい。今後 スタッフページで新たな日本語名のメンバーが追加されると目立つケース事があるかもと思ってます )
↓読み込み完了まで、フォントが文字化けしている
|  safari  |  chrome  |
| ---- | ---- |
| ![FlutterKaigi 2021 2021-09-24 17-52-37](https://user-images.githubusercontent.com/885696/134649295-8b9d7734-9089-4f56-aa3a-e92f5d028ad5.png) |  ![FlutterKaigi 2021 2021-09-24 17-52-06](https://user-images.githubusercontent.com/885696/134649337-8808a52e-c829-4957-ac8c-7a2f7ca48746.png) |
https://user-images.githubusercontent.com/885696/134649926-fa922174-8771-4b02-baea-24ade2e71ae5.mov
↓漢字が中華フォントになっている
| safari  |  chrome  |
| …
=> change renderer to html

lib/l10n/app_en.arb, lib/l10n/app_ja.arb, lib/widgets/footer.dart, pubspec.lock, pubspec.yaml
- Disclaimer and Trademark add to footer
- Add styled_text
- Update library version
=> add: disclaimer and trademark

lib/l10n/app_ja.arb
- change dena's japanese name format
- "株式会社 DeNA" → "株式会社ディー・エヌ・エー"
=> fix: change dena's name format (only japanese)

lib/pages/session.dart
https://github.com/FlutterKaigi/confwebsite2021/issues/74
=> padding を設定することで重なりを防ぐ

lib/l10n/app_en.arb, lib/l10n/app_ja.arb, lib/pages/index.dart
=> イベントを無事に終え感謝の念に変更
